apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: factoryflow
type: Opaque
stringData:
  username: admin
  password: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: factoryflow
spec:
  replicas: 1
  strategy:
    type: RollingUpdate     # Deployment strategy as RollingUpdate, which gradually replaces old pods with new ones to minimize downtime.
    rollingUpdate:
      maxUnavailable: 1     # Maximum number of pods that can be unavailable during the update process. In this case, at most 1 pod can be unavailable at any given time.
      maxSurge: 1           # Maximum number of pods that can be created during the update process. In this case, at most 1 additional pod can be created at any given time.
  selector:
    matchLabels:
      app: rabbitmq         # Label selector to identify the pods managed by this deployment. In this case, it matches pods with the label "app: rabbitmq".
  template:
    metadata:
      labels:
        app: rabbitmq       # Label to identify the pods created by this deployment. In this case, it assigns the label "app: rabbitmq" to the pods.
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        resources:    # adcionado para evitar: One or more containers do not have resources - this can cause noisy neighbor issues
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: factoryflow
spec:
  type: ClusterIP   # (default) ClusterIP: Exposes the service on a cluster-internal IP. Choosing this value makes the service only reachable from within the cluster.
  #type: LoadBalancer  # LoadBalancer: Exposes the service externally using a cloud provider's load balancer. The external IP address will be provisioned by the cloud provider.
  #type: NodePort  # NodePort: Exposes the service on each Node's IP at a static port (the NodePort). A ClusterIP service, to which the NodePort service routes, is automatically created.
  selector:
    app: rabbitmq
  ports:
  - name: amqp        # Name of the port for the AMQP protocol, which is used for messaging between clients and the RabbitMQ server.
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: web         # Name of the port for the RabbitMQ management web interface, which provides a web-based UI for monitoring and managing RabbitMQ.
    protocol: TCP
    port: 15672
    targetPort: 15672
